config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'urls#default'
  resources :urls
  get '/:alias', to: 'urls#redir'

end

app/models/url.rb
# encoding: US-ASCII
class Url < ActiveRecord::Base
  validates :redir_limit, numericality: { only_integer: true }
  validates :redirect_to, format: { with: /\A(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x00a1-\xffff0-9]-*)*[a-z\x00a1-\xffff0-9]+)(?:\.(?:[a-z\x00a1-\xffff0-9]-*)*[a-z\x00a1-\xffff0-9]+)*(?:\.(?:[a-z\x00a1-\xffff]{2,})).?)(?::\d{2,5})?(?:[\/?#]\S*)?\z/,
    message: "is an invalid URL" }
  validates :alias, uniqueness: true
  validates :alias, length: {in: 4..20}
  validates :alias, format: {with: /[a-zA-Z0-9]+/}
  validates :redirect_to, presence: true
  
  BASECHARS = [('0'..'9').to_a,('A'..'Z').to_a,('a'..'z').to_a].flatten
  
  URL_PROTOCOL_HTTP = "http://"
  REGEX_LINK_HAS_PROTOCOL = Regexp.new('\Ahttp:\/\/|\Ahttps:\/\/', Regexp::IGNORECASE)
  
  def self.clean_url(url)
    return nil if url.blank?
    url = URL_PROTOCOL_HTTP + url.strip unless url =~ REGEX_LINK_HAS_PROTOCOL
    URI.parse(url).normalize.to_s
  end
  
  def self.generate_alias
    unique = false
    while unique == false
      randalias = (0..5).map {BASECHARS[rand(61)]}.join
      if !self.find_by({alias: randalias})
        unique = true
      end
    end
    randalias
  end
  
  def self.createlink(*args)
    create = Url.new(*args).save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def after_sign_in_path_for(resource)
      urls_path
    end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:default, :redir, :create]
  # GET /
  def default
    if user_signed_in? 
        redirect_to urls_path
    end
    @url = Url.new
  end
  
  # GET /alias
  def redir
    str_alias = params[:alias]
    link = Url.find_by({alias: str_alias})
    if link != nil
    link.views += 1
      case link.redir_id
      when 0
        raise ActiveRecord::RecordNotFound
      when 1
      when 2
        if link.views >= link.redir_limit
          link.redir_id = 0
        end

      else
      end
        link.save
        redirect_to link.redirect_to, :status => :moved_permanently
    else
      raise ActiveRecord::RecordNotFound
      
      # render :file => "#{Rails.root}/public/404.html",  :status => 404
      # raise ActionController::RoutingError.new('Not Found')
    end
    # respond_to do |format|
      # format.html { render :text => link }
    # end
  end

  # GET /urls
  # GET /urls.json
  def index
    
    #@urls = Url.all#current_user.urls.all
    get_urls
    @url = Url.new
  end

  # GET /urls/1
  # GET /urls/1.json
  # def show
  # end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
    if @url.user_id != current_user.id
      respond_to do |format|
        format.html { redirect_to urls_path, notice: 'You don\'t have permission to edit this url.' }
        format.json { render :show, status: :ok, location: urls_path }
      end
    end
  end

  # POST /urls
  # POST /urls.json
  def create
    param_name = url_params[:name]
    param_redirect_to = Url.clean_url(url_params[:redirect_to])
    param_alias = url_params[:alias]
    redir_id = 1
    
    if !url_params[:redir_val1].blank?
      redir_id += 1
    end
    param_redir_limit = (url_params[:redir_limit].blank? ? '1' : url_params[:redir_limit].dup )

    if param_alias.blank?
      param_alias = Url.generate_alias.dup
    end
    
    @url = Url.new({name: param_name, redirect_to: param_redirect_to, alias: param_alias,
       user_id: user_signed_in? ? current_user.id : nil, redir_id: redir_id, redir_limit: param_redir_limit})
       
    respond_to do |format|
      if @url.save
        format.html { redirect_to request.referer, notice: 'Your URL is: ' + request.base_url + '/' + @url.alias}
        format.json { render :show, status: :created, location: request.referer }
      else
        format.html { render user_signed_in? ? :index : :default }
        format.json { render json: @url.errors, status: :unprocessable_entity }
        if user_signed_in?
          get_urls
        end
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.user_id == current_user.id
        param_name = url_params[:name]
        param_redirect_to = Url.clean_url(url_params[:redirect_to])
        param_alias = url_params[:alias]
        redir_id = 1
        
        if !url_params[:redir_val1].blank?
          redir_id += 1
          redir_limit = (url_params[:redir_limit].blank? ? 1: url_params[:redir_limit].to_i)
        end
        
        if @url.update({name: param_name, redirect_to: param_redirect_to,
        redir_id: redir_id, redir_limit: redir_limit})
          format.html { redirect_to request.referer, notice: 'Url was successfully updated.' }
          format.json { render :show, status: :ok, location: request.referer }
        else
          format.html { render :edit }
          format.json { render json: @url.errors, status: :unprocessable_entity }
        end
        
      else
        format.html { redirect_to urls_path, notice: 'You don\'t have permission to edit this url.' }
        format.json { render :show, status: :ok, location: urls_path }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    if @url.user_id == current_user.id
      @url.destroy
      respond_to do |format|
        format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to urls_url, notice: 'You don\'t have permission to delete this url.' }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end
    
    def get_urls
      @urls = current_user.urls.order(redir_id: :desc).all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
    	if user_signed_in?
	      params.require(:url).permit(:name, :redirect_to, :alias, :redir_val1, :redir_limit)
    	else
	      params.require(:url).permit(:redirect_to, :redir_val1)
    	end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Disposable URL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="top-bar" data-topbar role="navigation">
	  <ul class="title-area">
	    <li class="name">
	      <h1><a href="/">Disposable URL</a></h1>
	    </li>
	     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
	    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	  </ul>
	
	  <section class="top-bar-section">
	    <!-- Right Nav Section -->
	    <ul class="right">
	    <% if user_signed_in? %>
        <li><a>Signed in as: <%= current_user.email%></a></li>	    
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	    <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
	    <% end %>
	    </ul>
	
	    <!-- Left Nav Section -->
	    <ul class="left">
	    <% if user_signed_in? %>
        <li><%= link_to "My URLs", urls_path %></li>
	    <% end %>
	    </ul>
	  </section>
	</nav>
	<% if notice %>
   <div data-alert class="alert-box info"><%= notice %></div>
  <% end %>
  <% if alert %>
   <div data-alert class="alert-box"><%= alert %></div>
  <% end %>
  <br>
<%= yield %>
  
<div class="footer">
  <div class="row">
    <p class="copyright">© 2015 sunbinyuan. All rights reserved.</p>
  </div>
</div>

</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <div class="row collapse">
    <div class="small-10 columns">
      <%= f.text_field :redirect_to, placeholder: 'Enter your URL...' %>
    </div>
    <div class="small-2 columns">
      <%= f.submit "Shrink", class: "button postfix" %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <%= check_box_tag "url[redir_val1]", 1, 'yes' %>
      <%= label_tag 'url[redir_val1]', 'One time clickable' %>
    </div>
    <a id="toggler">More options</a>
  </div>
  <div class="row more" style="display: none">
    <div class="small-6 columns small-centered">
      <div class="row">
        <div class="small-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row">
        <div class="small-12 columns">
          <%= f.label :alias %>
          <%= f.text_field :alias %>
        </div>
      </div>
      <div class="row">
        <div class="small-12 columns">
          <%= f.label :redir_limit %>
          <%= f.text_field :redir_limit %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/urls/_form_edit.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="row">
    <%= f.label :redirect_to %><br>
    <%= f.text_field :redirect_to %>
  </div>
  <div class="row">
    <%= check_box_tag "url[redir_val1]", 1, 'yes' %>
    <%= label_tag 'url[redir_val1]', 'One time clickable' %>
  </div>
  <div class="row">
    <%= f.label :redir_limit %><br>
    <%= f.text_field :redir_limit %>
  </div>
  <div class="row">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/default.html.erb
<% if @url.errors.any? %>
  <div data-alert class="alert-box alert">
    <%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:

    <% @url.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    
  </div>
<% end %>  
  
<div class="row">
  <h2>Disposable URL</h2>
  <h4>Throw your URLs away after being viewed!</h4>
</div>

<%= form_for(@url) do |f| %>
<div class="row">
<div class="large-12 columns">
  <div class="callout panel">

  <div class="row collapse">
    
    <div class="small-10 columns">
      <%= f.text_field :redirect_to, placeholder: 'Enter your URL...' %>
    </div>
    <div class="small-2 columns">
      <%= f.submit "Shrink", class: "button postfix" %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <%= check_box_tag "url[redir_val1]", 1, 'yes' %>
      <%= label_tag 'url[redir_val1]', 'One time clickable' %>
    </div>
  </div>
  </div>
</div>
</div>
  
<% end %>
<div class="row">
  <div class="large-12 columns">
    <div class="panel">
      <h3>What is Disposable URL? </h3>
      <p>Disposable URL is the URL shortener that let you choose the number of time your link can be viewed before it goes inactive.</p>
      <p>By default, a guest can only make a normal or a one-time shortened URL. By signing up, you can customize and manage your links.</p>
      <p>Follow us on social media!</p>
      <div class="row">
        <div class="large-4 medium-4 columns">
          <p><a href="http://foundation.zurb.com/docs">Foundation Documentation</a><br>Everything you need to know about using the framework.</p>
        </div>
        <div class="large-4 medium-4 columns">
          <p><a href="http://zurb.com/university/code-skills">Foundation Code Skills</a><br>These online courses offer you a chance to better understand how Foundation works and how you can master it to create awesome projects.</p>
        </div>
        <div class="large-4 medium-4 columns">
          <p><a href="http://foundation.zurb.com/forum">Foundation Forum</a><br>Join the Foundation community to ask a question or show off your knowlege.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/urls/edit.html.erb
<% if @url.errors.any? %>
  <div data-alert class="alert-box alert">
    <%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:

    <% @url.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    
  </div>
<% end %>
<div class="row">
  <h4>Editing Url</h4>
</div>

<%= form_for(@url) do |f| %>
  <div class="row">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="row">
    <%= f.label :redirect_to %>
    <%= f.text_field :redirect_to %>
  </div>
  <div class="row">
    <%= check_box_tag "url[redir_val1]", 1, (@url.redir_id - 1) > 0 ? 'yes' : nil %>
    <%= label_tag 'url[redir_val1]', 'One time clickable' %>
  </div>
  <div class="row">
    <%= f.label :redir_limit %>
    <%= f.text_field :redir_limit %>
  </div>
  <div class="row">
    <%= f.submit 'Update', class: "button"%>
  </div>
<% end %>
<div class="row">
  <%= link_to 'Back', urls_path %>
</div>

app/views/urls/index.html.erb
<% if @url.errors.any? %>
  <div data-alert class="alert-box alert">
    <%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:

    <% @url.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    
  </div>
<% end %>
<br>
<%= render 'form' %>
<div class="row">
  <h4>Your URLs</h4>
</div>

<div class="row">
  <div class="large-9 columns">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Redirect to</th>
          <th>Link</th>
          <th>Views</th>
          <th>Redirect times</th>
          <th colspan="2"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @urls.each do |url| %>
          <tr class="redir_<%= url.redir_id %>">
            <td><%= url.name %></td>
            <td><%= link_to(url.redirect_to[0...20] + (url.redirect_to.length > 20 ? '...' : nil.to_s), url.redirect_to) %></td>
            <td><%= link_to(request.base_url + '/' + url.alias, request.base_url + '/' + url.alias) %></td>
            <td><%= url.views %></td>
            <td><%= url.redir_limit %></td>
            <td><%= link_to 'Edit', edit_url_path(url) %></td>
            <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="large-3 columns">
    <div class="panel">
      <ul class="no-bullet">
        <li><span style="font-size:1em; padding-left:1em; background:#e7e7e7;">&nbsp;</span> Gray - Inactive</li>
        <li><span style="font-size:1em; padding-left:1em; background:#43AC6A;">&nbsp;</span> Green - Unlimited views</li>
        <li><span style="font-size:1em; padding-left:1em; background:#f08a24;">&nbsp;</span> Orange - Limited views</li>
      </ul>
      
    </div>
    
  </div>
</div>
<br>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @url.name %>
</p>

<p>
  <strong>Redirect to:</strong>
  <%= @url.redirect_to %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @url.alias %>
</p>

<p>
  <strong>Views:</strong>
  <%= @url.views %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to(request.base_url + '/' + @url.alias, request.base_url + '/' + @url.alias) %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>